importScripts("./ngsw-worker.js"); // generated by Angular build process

importScripts("./service-worker/sw-schema.js");
importScripts("./service-worker/sw-db.js");
importScripts("./service-worker/sw-utils.js");

// tareas asíncronas
self.addEventListener("sync", (e) => {
  let respuesta;
  const key = e.tag.split('sync')[1]
  const storageSync = e.tag.split('sync')[0]
  switch( storageSync ){

    case swSchema.storages.listaDescripcionPedidos :
        respuesta = enviarData( storageSync, key );
    break;
    case swSchema.storages.subidaImagenes :
      respuesta = enviarData( storageSync, key );
      break;
    default:
    break;
  }

    e.waitUntil(respuesta);

});
